apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: microservices
type: Opaque
data:
  # Default values (base64 encoded)
  # To change: echo -n 'your-password' | base64
  
  # postgres / postgres
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  
  # Database names
  INVENTORY_DB_NAME: aW52ZW50b3J5X2Ri
  BILLING_DB_NAME: YmlsbGluZ19kYg==