apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: microservices
type: Opaque
data:
  # Default values (base64 encoded)
  # To change: echo -n 'your-password' | base64
  
  # admin / admin123
  RABBITMQ_USER: YWRtaW4=
  RABBITMQ_PASSWORD: YWRtaW4xMjM=
  
  # Queue name: payment_queue
  RABBITMQ_QUEUE: cGF5bWVudF9xdWV1ZQ==